#!/usr/bin/env python3
"""Generate env.env from builds.toml.

The generated file keeps the ``source env.env`` ergonomics: it resolves
ARTIFACT_ROOT and the python binary suffix at source-time so the same file
works on the host and inside the container. Only the variable *names* and
relative path segments come from the manifest, so paths stay portable.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import artifact_config as cfg  # noqa: E402
import console  # noqa: E402

HEADER = """\
# GENERATED by scripts/update/0_generate_env.py from builds.toml.
# Do not edit by hand; edit builds.toml and regenerate.

# Resolve snapshot paths from this env file location so the file is portable
# across host and container workspaces. Callers can still override any path.
ARTIFACT_ROOT="$(
  cd "$(dirname "${BASH_SOURCE[0]:-${0}}")" \\
  && pwd -P
)"
_PYTHON_BIN_SUFFIX=""
case "$(uname -s)" in
  CYGWIN*|MINGW*|MSYS*|Darwin)
    _PYTHON_BIN_SUFFIX=".exe"
    ;;
esac
"""

FOOTER = """\
# Stop streamlit from collecting usage data (Why is this the default to begin with...)
export STREAMLIT_BROWSER_GATHER_USAGE_STATS=0

unset _PYTHON_BIN_SUFFIX
"""


def render(config: cfg.Config) -> str:
    lines = [HEADER, "# Variant source snapshots"]
    for variant in config.variants:
        name = variant.name.upper()
        lines.append(
            f'export {name}_PYTHON_DIR="${{ARTIFACT_ROOT}}/snapshots/cpython-{variant.name}"'
        )

    lines.append("")
    lines.append("# Builds (config x variant)")
    for build in config.builds:
        p = build.env_prefix
        lines.append(
            f'export {p}_BUILD_DIR="${{ARTIFACT_ROOT}}/build/cpython-{build.id}"'
        )
        lines.append(
            f'export {p}_PYTHON_BIN="${{{p}_BUILD_DIR}}/python${{_PYTHON_BIN_SUFFIX}}"'
        )
        lines.append(
            f'export {p}_PYTHON_ENV="${{ARTIFACT_ROOT}}/build/venv-{build.id}"'
        )
        lines.append(
            f'export {p}_PYTHON_ENV_ACTIVATE="${{{p}_PYTHON_ENV}}/bin/activate"'
        )
        lines.append("")

    lines.append("# Stable interpreter (website, plots, pyperformance tooling)")
    lines.append('export STABLE_PYTHON_ENV="${ARTIFACT_ROOT}/build/venv-stable"')
    lines.append('export STABLE_PYTHON_BIN="${STABLE_PYTHON_ENV}/bin/python"')
    lines.append('export STABLE_PYTHON_ENV_ACTIVATE="${STABLE_PYTHON_ENV}/bin/activate"')
    lines.append("")
    lines.append(FOOTER)
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    config = cfg.load()
    out_path = cfg.ARTIFACT_ROOT / "env.env"
    out_path.write_text(render(config))
    console.success(f"wrote {out_path} ({len(config.builds)} builds)")


if __name__ == "__main__":
    main()
