#!/usr/bin/env bash

set -euo pipefail

BASELINE_REPO="git@github.com:python/cpython.git"
BASELINE_REF="aeff92d86a3"

PATCHED_REPO="git@github.com:fxpl/cpython.git"
PATCHED_REF="codegen"

OUTPUT_DIR="snapshots"
FORCE=1

SCRIPT_NAME="$(basename "$0")"

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [options]

Options:
  --no-force                Fail if snapshot directories already exist
  -h, --help                Show this help
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

resolve_ref_to_commit() {
  local repo_dir="$1"
  local ref="$2"

  git -C "$repo_dir" rev-parse --verify "$ref^{commit}" 2>/dev/null \
    || git -C "$repo_dir" rev-parse --verify "refs/tags/$ref^{commit}" 2>/dev/null \
    || git -C "$repo_dir" rev-parse --verify "refs/heads/$ref^{commit}" 2>/dev/null \
    || git -C "$repo_dir" rev-parse --verify "refs/remotes/origin/$ref^{commit}" 2>/dev/null \
    || die "could not resolve ref '$ref' in repo '$repo_dir'"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-force)
      FORCE=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

require_cmd git
require_cmd mktemp
require_cmd sed
require_cmd tar

mkdir -p "$OUTPUT_DIR"

BASELINE_DIR="$OUTPUT_DIR/cpython-baseline"
PATCHED_DIR="$OUTPUT_DIR/cpython-patched"

if [ "$FORCE" -eq 0 ]; then
  [ ! -e "$BASELINE_DIR" ] || die "$BASELINE_DIR exists; remove it or rerun without --no-force"
  [ ! -e "$PATCHED_DIR" ] || die "$PATCHED_DIR exists; remove it or rerun without --no-force"
fi

TMP_ROOT="$(mktemp -d -t cpython-snapshots-XXXXXX)"
cleanup() {
  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

BASELINE_CLONE_DIR="$TMP_ROOT/baseline-repo"
PATCHED_CLONE_DIR="$TMP_ROOT/patched-repo"

export_snapshot() {
  local name="$1"
  local repo="$2"
  local ref="$3"
  local target_dir="$4"
  local clone_dir="$5"
  local commit

  echo "[info] cloning $name repo: $repo"
  git clone --no-checkout "$repo" "$clone_dir"

  echo "[info] resolving $name ref: $ref"
  commit="$(resolve_ref_to_commit "$clone_dir" "$ref")"

  if [ "$FORCE" -eq 1 ]; then
    rm -rf "$target_dir"
  fi
  mkdir -p "$target_dir"

  echo "[info] exporting $name snapshot to: $target_dir"
  git -C "$clone_dir" archive --format=tar "$commit" | tar -xf - -C "$target_dir"
}

export_snapshot "baseline" "$BASELINE_REPO" "$BASELINE_REF" "$BASELINE_DIR" "$BASELINE_CLONE_DIR"
export_snapshot "patched" "$PATCHED_REPO" "$PATCHED_REF" "$PATCHED_DIR" "$PATCHED_CLONE_DIR"

BASELINE_COMMIT="$(resolve_ref_to_commit "$BASELINE_CLONE_DIR" "$BASELINE_REF")"
BASELINE_DATE="$(git -C "$BASELINE_CLONE_DIR" show -s --format=%cI "$BASELINE_COMMIT")"
PATCHED_COMMIT="$(resolve_ref_to_commit "$PATCHED_CLONE_DIR" "$PATCHED_REF")"
PATCHED_DATE="$(git -C "$PATCHED_CLONE_DIR" show -s --format=%cI "$PATCHED_COMMIT")"
RUN_AT_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

{
  cat <<EOF
# Generated by $SCRIPT_NAME at $RUN_AT_UTC
BASELINE_REPO=$BASELINE_REPO
BASELINE_REF=$BASELINE_REF
BASELINE_COMMIT=$BASELINE_COMMIT
PATCHED_REPO=$PATCHED_REPO
PATCHED_REF=$PATCHED_REF
PATCHED_COMMIT=$PATCHED_COMMIT
EOF
} > "$OUTPUT_DIR/info.txt"

cat <<EOF
[done] snapshots created
  baseline: $BASELINE_DIR ($BASELINE_COMMIT)
  patched:  $PATCHED_DIR ($PATCHED_COMMIT)
EOF
